/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    screens: {
      "3xs": "320px",
      "2xs": "425px",
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
      "3xl": "1920px",
    },
    extend: {
      colors: {
        primary: {
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          950: "var(--color-primary-950)",
        },
        "light-bg": "#F9FAFB",
        "light-text": "#1F2937",
        "light-accent": "#3B82F6",
        "dark-bg": "#111827",
        "dark-text": "#E5E7EB",
        "dark-accent": "#60A5FA",
        "fantasy-bg": "#1E293B",
        "fantasy-text": "#9CA3AF",
        "fantasy-accent": "#8B5CF6",
      },
    },
  },
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
  ],
};
