//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, ExistsArgs as $ExistsArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type ContactSubmissionFindManyArgs = $FindManyArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionFindUniqueArgs = $FindUniqueArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionFindFirstArgs = $FindFirstArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionExistsArgs = $ExistsArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionCreateArgs = $CreateArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionCreateManyArgs = $CreateManyArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionUpdateArgs = $UpdateArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionUpdateManyArgs = $UpdateManyArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionUpsertArgs = $UpsertArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionDeleteArgs = $DeleteArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionDeleteManyArgs = $DeleteManyArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionCountArgs = $CountArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionAggregateArgs = $AggregateArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionGroupByArgs = $GroupByArgs<$Schema, "ContactSubmission">;
export type ContactSubmissionWhereInput = $WhereInput<$Schema, "ContactSubmission">;
export type ContactSubmissionSelect = $SelectInput<$Schema, "ContactSubmission">;
export type ContactSubmissionInclude = $IncludeInput<$Schema, "ContactSubmission">;
export type ContactSubmissionOmit = $OmitInput<$Schema, "ContactSubmission">;
export type ContactSubmissionGetPayload<Args extends $SelectIncludeOmit<$Schema, "ContactSubmission", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "ContactSubmission", Args, Options>;
