#!/usr/bin/env bash
# wt-new.sh — create a new git worktree for parallel Claude/dev sessions.
#
# Usage:
#   ./scripts/wt-new.sh <branch-name> [--from <base-branch>] [--port <n>]
#
# Examples:
#   ./scripts/wt-new.sh feature-auth
#   ./scripts/wt-new.sh feature-billing --from main --port 3002
#
# What it does:
#   1. Creates a worktree at ../<repo>-<branch> on a new branch <branch-name>.
#   2. Copies .env and GEMINI.md (if they exist) into the worktree.
#   3. Picks a free PORT (3001+) and writes it into <worktree>/.env.local
#      so `pnpm dev` doesn't collide with the main session.
#   4. Runs `pnpm install` in the new worktree (shares pnpm store, fast).
#   5. Prints next-step commands.

set -euo pipefail

# --- arg parsing ---------------------------------------------------------
if [[ $# -lt 1 || "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'
  exit 0
fi

BRANCH="$1"; shift
BASE=""
PORT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --from)  BASE="$2"; shift 2 ;;
    --port)  PORT="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

# --- repo discovery ------------------------------------------------------
REPO_ROOT="$(git rev-parse --show-toplevel)"
REPO_NAME="$(basename "$REPO_ROOT")"
PARENT_DIR="$(dirname "$REPO_ROOT")"
WT_PATH="$PARENT_DIR/${REPO_NAME}-${BRANCH}"

if [[ -e "$WT_PATH" ]]; then
  echo "error: $WT_PATH already exists" >&2
  exit 1
fi

# --- pick a free port if not provided ------------------------------------
pick_port() {
  local p=3001
  while ss -ltn "( sport = :$p )" 2>/dev/null | grep -q ":$p" \
        || git worktree list --porcelain | grep -qE "PORT=$p\b" 2>/dev/null; do
    p=$((p+1))
  done
  echo "$p"
}
[[ -z "$PORT" ]] && PORT="$(pick_port)"

# --- create the worktree --------------------------------------------------
echo "→ creating worktree: $WT_PATH (branch: $BRANCH${BASE:+ from $BASE})"
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  git worktree add "$WT_PATH" "$BRANCH"
elif [[ -n "$BASE" ]]; then
  git worktree add -b "$BRANCH" "$WT_PATH" "$BASE"
else
  git worktree add -b "$BRANCH" "$WT_PATH"
fi

# --- copy env, GEMINI.md, set port ----------------------------------------
if [[ -f "$REPO_ROOT/.env" ]]; then
  cp "$REPO_ROOT/.env" "$WT_PATH/.env"
  echo "→ copied .env"
fi

if [[ -f "$REPO_ROOT/GEMINI.md" ]]; then
  cp "$REPO_ROOT/GEMINI.md" "$WT_PATH/GEMINI.md"
  echo "→ copied GEMINI.md"
fi

cat > "$WT_PATH/.env.local" <<EOF
# auto-generated by scripts/wt-new.sh
PORT=$PORT
EOF
echo "→ wrote .env.local with PORT=$PORT"

# --- install deps --------------------------------------------------------
if command -v pnpm >/dev/null 2>&1; then
  echo "→ pnpm install (shared store, should be fast)"
  (cd "$WT_PATH" && pnpm install --prefer-offline --silent)
else
  echo "warn: pnpm not found, skipping install" >&2
fi

# --- summary -------------------------------------------------------------
cat <<EOF

✓ worktree ready

  path:    $WT_PATH
  branch:  $BRANCH
  port:    $PORT

next steps:
  cd $WT_PATH
  pnpm dev          # runs on http://localhost:$PORT
  claude            # start a separate Claude session here

cleanup when done:
  git worktree remove $WT_PATH
  git branch -d $BRANCH    # if merged
EOF